spring:
  datasource:
    username: polsoftex-admin
    password: Haslo123
    url: jdbc:sqlserver://zdrowejedzenie.database.windows.net:1433;database=zdrowejedzenie-orders
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
