apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zdrowejedzenie-orders
  name: zdrowejedzenie-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zdrowejedzenie-orders
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zdrowejedzenie-orders
    spec:
      containers:
        - image: polregistry.azurecr.io/zdrowejedzenie-orders:latest
          name: zdrowejedzenie-orders
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zdrowejedzenie-orders
  name: zdrowejedzenie-orders
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: zdrowejedzenie-orders
  type: ClusterIP
